### ISSUE TITLE
Unexpected hard fork stops at 137270

### ISSUE THREAD

**Issue by kanshi** [deso-protocol/core#375]
Good morning :)

```
E0611 07:39:38.502743       1 blockchain.go:1380] MarkBlockInvalid: Block height: 137270, Block hash: 0000000000005dccb1a6675663df02806d2638e3a3ddf5b9c0be7b6b903b19ba, Error: ConnectBlock: : ConnectTransaction: : RuleErrorInputSpendsNonexistentUtxo
E0611 07:39:38.502761       1 blockchain.go:1381] MarkBlockInvalid: Printing stack trace so error is easy to find: 
E0611 07:39:38.502783       1 blockchain.go:1382] goroutine 142917 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
github.com/deso-protocol/core/lib.(*Blockchain).MarkBlockInvalid(0x1850a40?, 0xc200c30fc0, {0xc3f2040d20, 0x49})
	/deso/src/core/lib/blockchain.go:1382 +0x12c
github.com/deso-protocol/core/lib.(*Blockchain).ProcessBlock(0xc0000787e0, 0xc3f0361b60, 0xd0?)
	/deso/src/core/lib/blockchain.go:2378 +0x33e5
github.com/deso-protocol/core/lib.(*Server)._handleBlock(0xc000a6a120, 0xc0015d0d80, 0xc3f0361b60)
	/deso/src/core/lib/server.go:1805 +0x768
github.com/deso-protocol/core/lib.(*Server)._handlePeerMessages(0xf4241?, 0x91ec3a?)
	/deso/src/core/lib/server.go:2117 +0x1cd
github.com/deso-protocol/core/lib.(*Server).messageHandler(0xc000a6a120)
	/deso/src/core/lib/server.go:2160 +0x1ad
created by github.com/deso-protocol/core/lib.(*Server).Start
	/deso/src/core/lib/server.go:2346 +0xac
```

**Comment by hz61p1** [comment]
Restart sync and index
