### ISSUE TITLE
Issue at Postgres sync block height 230799 

### ISSUE THREAD

**Issue by mvanhalen** [deso-protocol/core#526]
We got an issue at height 230799. 

`I0512 11:01:55.167374       1 server.go:1749] Server._handleBlock: Received block ( 230799 / 231934 ) from Peer [ Remote Address: 34.123.41.111:17000 PeerID=63 ]
E0512 11:01:55.177355       1 blockchain.go:1384] MarkBlockInvalid: Block height: 230799, Block hash: 0000000000003f043874f22f3b5c04259936b92006a77984584bc5c2a2941067, Error: ConnectBlock: error connecting txn #1: ConnectTransaction: : _connectBasicTransferWithExtraSpend : RuleErrorCreatorCoinTransferPostAlreadyHasSufficientDiamonds
E0512 11:01:55.177377       1 blockchain.go:1385] MarkBlockInvalid: Printing stack trace so error is easy to find: 
E0512 11:01:55.177406       1 blockchain.go:1386] goroutine 1547 [running]:`

@lazynina @AeonSw4n 

Syncing can become quite slow as well. Might be related to some indexes that need tuning. We are testing some which might help.

**Comment by erwin-willems** [comment]
We had the same issue (before I did a full resync which isn't on this block yet):

```
May  9 21:10:19 post2earn docker/backend-green[1354]: E0509 19:10:19.893513       1 blockchain.go:1384] MarkBlockInvalid: Block height: 230799, Block hash: 0000000000003f043874f22f3b5c04259936b92006a77984584b
c5c2a2941067, Error: ConnectBlock: error connecting txn #27: ConnectTransaction: : _connectBasicTransferWithExtraSpend Problem spending balance: _spendBalance: amountNanos (53665621002) exceeds spendable balance (53565653535) at tipHeight (230798): RuleErrorInsufficientBalance
May  9 21:10:19 post2earn docker/backend-green[1354]: E0509 19:10:19.893534       1 blockchain.go:1385] MarkBlockInvalid: Printing stack trace so error is easy to find:
May  9 21:10:19 post2earn docker/backend-green[1354]: E0509 19:10:19.893556       1 blockchain.go:1386] goroutine 1685 [running]:
May  9 21:10:19 post2earn docker/backend-green[1354]: runtime/debug.Stack()
May  9 21:10:19 post2earn docker/backend-green[1354]: #011/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
May  9 21:10:19 post2earn docker/backend-green[1354]: github.com/deso-protocol/core/lib.(*Blockchain).MarkBlockInvalid(0x1a39a60?, 0xc31ccb8f40, {0xc002d87700, 0x100})
May  9 21:10:19 post2earn docker/backend-green[1354]: #011/deso/src/core/lib/blockchain.go:1386 +0x12c
May  9 21:10:19 post2earn docker/backend-green[1354]: github.com/deso-protocol/core/lib.(*Blockchain).ProcessBlock(0xc000444000, 0xc0e5660cf0, 0xd0?)
May  9 21:10:19 post2earn docker/backend-green[1354]: #011/deso/src/core/lib/blockchain.go:2394 +0x34a5
May  9 21:10:19 post2earn docker/backend-green[1354]: github.com/deso-protocol/core/lib.(*Server)._handleBlock(0xc0006766c0, 0xc3cb5c8000, 0xc0e5660cf0)
May  9 21:10:19 post2earn docker/backend-green[1354]: #011/deso/src/core/lib/server.go:1823 +0x768
May  9 21:10:19 post2earn docker/backend-green[1354]: github.com/deso-protocol/core/lib.(*Server)._handlePeerMessages(0xf4241?, 0x4000001e2c6a?)
May  9 21:10:19 post2earn docker/backend-green[1354]: #011/deso/src/core/lib/server.go:2142 +0x1dc
May  9 21:10:19 post2earn docker/backend-green[1354]: github.com/deso-protocol/core/lib.(*Server).messageHandler(0xc0006766c0)
May  9 21:10:19 post2earn docker/backend-green[1354]: #011/deso/src/core/lib/server.go:2187 +0x1ad
May  9 21:10:19 post2earn docker/backend-green[1354]: created by github.com/deso-protocol/core/lib.(*Server).Start
May  9 21:10:19 post2earn docker/backend-green[1354]: #011/deso/src/core/lib/server.go:2375 +0xaf
May  9 21:10:19 post2earn docker/backend-green[1354]: E0509 19:10:19.893559       1 blockchain.go:1393] MarkBlockInvalid: Not marking blocks invalid for now because it makes debugging easier
May  9 21:10:19 post2earn docker/backend-green[1354]: E0509 19:10:19.893827       1 server.go:1743] Server._handleBlock: Encountered an error processing block <Header: < 231047, 00000000000057eae34102bdcbf46f
4e579bf58c14dfe22dd6fdd4b7f32efc91, 1 >, Signer Key: BC1YLh768bVj2R3QpSiduxcvn7ipxF3L3XHsabZYtCGtsinUnNrZvNN>. Disconnecting from peer [ Remote Address: 35.232.92.5:17000, DISCONNECTED PeerID=1 ]: Error while
 processing block: : ProcessBlock: Problem trying to attach block (< TstampSecs: 1683577664, Height: 230800, Hash: 0000000000000ec042465464a0fb566b18d9565fcece6d2165206437a2f919a2, ParentHash 0000000000003f04
3874f22f3b5c04259936b92006a77984584bc5c2a2941067, Status: HEADER_VALIDATED | BLOCK_PROCESSED | BLOCK_STORED, CumWork: 93065394772280397008>) in reorg: ConnectBlock: Parent hash of block being connected does not match tip
May  9 21:10:19 post2earn docker/backend-green[1354]: I0509 19:10:19.893864       1 server.go:1749] Server._handleBlock: Received block ( 231048 / 231131 ) from Peer [ Remote Address: 35.232.92.5:17000, DISCONNECTED PeerID=1 ]
```

**Comment by lazynina** [comment]
@mvanhalen @erwin-willems - passed block 230799 with PR #532  , just going to get another set of eyes on it but that should address the issue with postgres marking that block invalid.

On the issue of slowness, I definitely experienced it as well. If you have any success with any of the indexing updates you apply, please let me know.

**Comment by lazynina** [comment]
@mvanhalen @erwin-willems - can you try the latest docket image? Just merged a PR that was able to sync past the problematic block height

**Comment by mvanhalen** [comment]
Will check it out thanks @lazynina FYI @kanshi
