### ISSUE TITLE
Postgres does not support most API queries

### ISSUE THREAD

**Issue by tijno** [deso-protocol/core#97]
@maebeam as per discord:

Syncing clean node via postgres, results in panic, after a certain height (15-20k ~ will try and identify specific point today).

Initially its fine in earlier blocks, but then it Panics.

Eg request:

`POST /api/v0/get-users-stateless HTTP/2`

`{"PublicKeysBase58Check":["BC1YLgxLrxvq5mgZUUhJc1gkG6pwrRCTbdT6snwcrsEampjqnSD1vck"],"SkipForLeaderboard":false}`

~~Results in this panic in logs:~~ (updated log in next reply)

**Comment by tijno** [comment]
Re ran full sync and zoomed in on the specific Height this seems to happen.

Between 15081 (last block i cloud load page without issues) and 15108 (block when i tried to reload page and it failed)

```
I0822 10:56:42.829752       1 server.go:3119] http: panic serving 172.24.0.4:35518: runtime error: invalid memory address or nil pointer dereference
goroutine 352632 [running]:
net/http.(*conn).serve.func1(0xc14940e780)
        /usr/lib/go/src/net/http/server.go:1804 +0x153
panic(0x1213440, 0x1f1e620)
        /usr/lib/go/src/runtime/panic.go:971 +0x499
github.com/bitclout/core/lib.(*UtxoView).GetPublicKeyForPKID(0xc12546fa40, 0xc14aefc090, 0x9, 0xc10b702e30, 0xb3500f)
        /bitclout/src/core/lib/block_view.go:4431 +0x1ca
github.com/bitclout/backend/routes._balanceEntryToResponse(0xc14aeb1420, 0x62890f, 0x0, 0x1f32680, 0xc12546fa40, 0xc14b170270, 0xc149449480)
        /bitclout/src/backend/routes/user.go:344 +0x65
github.com/bitclout/backend/routes.(*APIServer).getMapFromEntries(0xc0002ec180, 0xc13b6a5a00, 0x2f, 0x40, 0x0, 0x0, 0x0, 0x0, 0xc12546fa40, 0xc14b170270, ...)
        /bitclout/src/backend/routes/user.go:329 +0x2d2
github.com/bitclout/backend/routes.(*APIServer).GetHodlYouMap(0xc0002ec180, 0xc149525110, 0x0, 0xc12546fa40, 0xc149525110, 0xc14afdaa00, 0x20)
        /bitclout/src/backend/routes/user.go:408 +0x1b1
github.com/bitclout/backend/routes.(*APIServer).updateUserFieldsStateless(0xc0002ec180, 0xc140fb1e40, 0xc12546fa40, 0x0, 0xc149524000, 0xc00037e000, 0x0)
        /bitclout/src/backend/routes/user.go:191 +0xe59
github.com/bitclout/backend/routes.(*APIServer).updateUsersStateless(0xc0002ec180, 0xc174805be8, 0x1, 0x1, 0x0, 0xc174805be8, 0x0, 0x1)
        /bitclout/src/backend/routes/user.go:98 +0x1b6
github.com/bitclout/backend/routes.(*APIServer).GetUsersStateless(0xc0002ec180, 0x18a1448, 0xc149448140, 0xc184476b00)
        /bitclout/src/backend/routes/user.go:55 +0x2f2
net/http.HandlerFunc.ServeHTTP(0xc000c18aa0, 0x18a1448, 0xc149448140, 0xc184476b00)
        /usr/lib/go/src/net/http/server.go:2049 +0x44
github.com/bitclout/backend/routes.Logger.func1(0x18a1448, 0xc149448140, 0xc184476b00)
        /bitclout/src/backend/routes/server.go:1040 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc0fbfe4900, 0x18a1448, 0xc149448140, 0xc184476b00)
        /usr/lib/go/src/net/http/server.go:2049 +0x44
github.com/bitclout/backend/routes.AddHeaders.func1(0x18a1448, 0xc149448140, 0xc184476b00)
        /bitclout/src/backend/routes/server.go:1117 +0x2f1
net/http.HandlerFunc.ServeHTTP(0xc0fbfe4930, 0x18a1448, 0xc149448140, 0xc184476b00)
        /usr/lib/go/src/net/http/server.go:2049 +0x44
github.com/unrolled/secure.(*Secure).Handler.func1(0x18a1448, 0xc149448140, 0xc184476b00)
        /root/go/pkg/mod/github.com/unrolled/secure@v1.0.8/secure.go:177 +0xda
net/http.HandlerFunc.ServeHTTP(0xc1494294e0, 0x18a1448, 0xc149448140, 0xc184476b00)
        /usr/lib/go/src/net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002ec3c0, 0x18a1448, 0xc149448140, 0xc184476900)
        /root/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
gopkg.in/DataDog/dd-trace-go.v1/contrib/internal/httputil.TraceAndServe(0x188a3e0, 0xc0002ec3c0, 0x18a0d88, 0xc149448140, 0xc184476800, 0x13a17a4, 0xa, 0xc149458820, 0x20, 0x0, ...)
        /root/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.29.0/contrib/internal/httputil/trace.go:43 +0x577
gopkg.in/DataDog/dd-trace-go.v1/contrib/gorilla/mux.(*Router).ServeHTTP(0xc000c19030, 0x18a0d88, 0xc12546f960, 0xc184476800)
        /root/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.29.0/contrib/gorilla/mux/mux.go:115 +0x231
net/http.serverHandler.ServeHTTP(0xc0fc1d6000, 0x18a0d88, 0xc12546f960, 0xc184476800)
        /usr/lib/go/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc14940e780, 0x18a4bb8, 0xc149448040)
        /usr/lib/go/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2993 +0x39b
```

**Comment by maebeam** [comment]
Thanks. I should've clarified in discord that almost no backend endpoints are supported at this moment. They will all be updated in the coming weeks.

**Comment by tijno** [comment]
Yeah aware of that and not unexpected. The change is quit considerable so will take time.

Profile page & wallet do work at the moment.

But from Height 15k something happens to cause these panics.

**Comment by tijno** [comment]
Just to confirm that this issue is still present with todays build.
